<?php

/**
 * Implements hook_permission().
 */
function ruf_test_permission() {
  return [
    'access ruf test page' => [
      'title' => t('Access Ruf Test Page'),
      'description' => t('The Ruf Test page'),
    ]
  ];
}

function ruf_test_menu() {
  $items['ruf/default'] = array(
    'title' => 'Overview page',
    'page callback' => 'ruf_test_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  $items['ruf/default/form'] = [
    'title' => 'Test Form hier jetzt',
    'page_callback' => 'drupal_get_form',
    'page_arguments' => array('ruf_test_form'),
    'access callback' => TRUE,
    'expanded' => TRUE,
  ];
  return $items;
}


function ruf_test_form($form, &$form_state) {
  $form['information'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
  ];
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Submit'),
  ];

  return $form;
}

function ruf_test_intro() {
  $markup = t('Ein bisschen Text, damit man was sieht.');
  return array('#markup' => $markup);
}
