<?php

/**
 * Implements hook_permission().
 */
function ruf_test_permission() {
  return [
    'access ruf test page' => [
      'title' => t('Access Ruf Test Page'),
      'description' => t('The Ruf Test page'),
    ]
  ];
}

function ruf_test_menu() {
  $items['ruf/default'] = array(
    'title' => 'Overview page',
    'page callback' => 'ruf_test_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  $items['wherewego'] = array(
    'title' => 'Why not',
    'description' => 'Test my form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}


function simple_form($form, &$form_state) {
  $form['description'] = [
    '#type' => 'item',
    '#title' => t('Vibecession biodiesel lomo listicle. Big mood sustainable poutine truffaut, hexagon crucifix selfies synth praxis '),
  ];
  $form['information'] = [
    '#type' => 'textfield',
    '#title' => 'Here we go',
  ];
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Submit'),
  ];

  return $form;
}

function simple_form_submit($form, &$form_state) {



//batch_set(ruf_test_batch_set());
  drupal_set_message(t('Creating some @somat nodes.', ['@somat' => 'Mei Liaba']), 'warning' );

}

function ruf_test_batch_set() {
  drupal_set_message('Creating some nodes.', 'status');

  $node_titles = [
    'Boot mit Auto',
    'Warum nicht wandern?',
    'Menschen machen Fehler',
    'Schildkröte rast auf Autobahn',
    'Warum ist die Rose rot?',
    'Die Abgeordneten machen einen Ausflug',
    'Freizeit ist für alle da',
    'Lasst uns in die Mensa gehen',
    'Freitag ist frei',
    'Fussball kann anstrengend sein',
    'Bayern ist ein Freistaat'
  ];

  foreach($node_titles as $title) {
    $operations[] = ['ruf_create_node',[$title]];
  }

  $batch = [
    'operations' => $operations,
    'finished'  => 'ruf_test_node_finished',
  ];

  return $batch;

}

function ruf_create_node($title, &$context) {

  // create the node
  global $user;
  $node = new stdClass();
  $node->type = 'page';
  $node->title = $title;
  node_object_prepare($node);
  $node->uid = $user->uid;
  $node->status = 1;
  $node = node_submit($node);
  node_save($node);
}

function ruf_test_node_finished($success, $results, $operations) {
  if($success) {

  }
}


function ruf_test_intro() {
  $markup = t('Ein bisschen Text, damit man was sieht.');
  return array('#markup' => $markup);
}
